version: '2'
services:
  mongodb:
    image: mongo:4.0.5
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    volumes:
    - ./data/db:/data/mongo
    ports:
    - 27017:27017
    command: mongod